/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package id.proyectotetris;
import javax.swing.JFrame;
import id.proyectotetris.GameTetris;
import java.awt.Color;
import java.awt.Graphics;
import java.util.Scanner;
import javax.swing.JPanel;
/**
 *
 * @author Max--
 */
public class TetrisPanelServer extends javax.swing.JPanel {

    /**
     * Creates new form TetrisPanel
     */
    public GameTetris g1;
    TCPServer50 mTcpServer;
    Scanner sc;
    public int[] puntajes= new int[10];
    public TetrisPanelServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                // Aquí llamamos a tu lógica de dibujo
                actualizarDibujoTablero(g);
            }
        };
        jLabel11 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Ingrese (a), (s), (d), (g), (u) ");

        jLabel2.setText("Puntajes");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel4.setText("IP");

        jTextField1.setText("127.0.0.1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("fil");

        jTextField3.setText("10");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setText("col");

        jTextField4.setText("20");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Port");

        jTextField5.setText("4444");

        jLabel10.setText("Jugador Ganador:");

        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        jLabel11.setText("JUGADOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel10)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addContainerGap(13, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButton1)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextField1ActionPerformed
    private void actualizarDibujoTablero(java.awt.Graphics g) {
        if (g1 == null || g1.tablero == null) return;
        int anchoPanel = jPanel1.getWidth(); 
        int altoPanel = jPanel1.getHeight();
        int tAncho = anchoPanel / g1.ancho;
        int tAlto = altoPanel / g1.alto;
        int t = Math.min(tAncho, tAlto);
        int xOffset = (anchoPanel - (g1.ancho * t)) / 2;
        int yOffset = (altoPanel - (g1.alto * t)) / 2;

        for (int i = 0; i < g1.alto; i++) {
            for (int j = 0; j < g1.ancho; j++) {
                String celda = g1.tablero[i][j];

                if (celda == null || celda.equals(" ") || celda.equals(".")) { 
                    continue; 
                }

                switch (celda) {
                    case "d" -> g.setColor(java.awt.Color.CYAN);    
                    case "i" -> g.setColor(java.awt.Color.ORANGE);  
                    case "c" -> g.setColor(java.awt.Color.YELLOW);  
                    case "l" -> g.setColor(java.awt.Color.MAGENTA); 
                    case "t" -> g.setColor(java.awt.Color.GREEN);   
                    case "v" -> g.setColor(java.awt.Color.RED);     
                    case "I" -> g.setColor(java.awt.Color.DARK_GRAY); 
                    case "=" -> g.setColor(java.awt.Color.GRAY);      
                    default  -> g.setColor(java.awt.Color.BLUE);
                }
                g.fillRect(xOffset + (j * t), yOffset + (i * t), t, t);

                g.setColor(java.awt.Color.BLACK);
                g.drawRect(xOffset + (j * t), yOffset + (i * t), t, t);
            }
        }
    }
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        g1 = new GameTetris();
        g1.ancho = Integer.parseInt(jTextField3.getText());
        g1.alto = Integer.parseInt(jTextField4.getText());
        g1.iniciarJuego(g1.ancho, g1.alto); 
        iniciarCicloJuego();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
        if(g1.turno%(mTcpServer.nrcli+1)==0){
            char tecla = evt.getKeyChar();
            switch (tecla) {
                case 'a' -> g1.moverIzquierda();
                case 's' -> g1.moverAbajo();
                case 'd' -> g1.moverDerecha();
                case 'g' -> g1.girarHorario();
                case 'u' -> g1.girarAntihorario();
            }
            enviarObjetos enviarObj = new enviarObjetos(g1,puntajes,mTcpServer.nrcli);
            ServidorEnvia(enviarObj);
//            g1.imprimir(g1.tablero);///
//            jPanel1.repaint();
        }
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        jPanel1.requestFocusInWindow();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed
    public void iniciarCicloJuego() {
        new Thread(() -> {
//            Scanner sc = new Scanner(System.in);
            puntajes[0]=0;
            
            while(true){
                if ((!g1.hayFicha && (g1.turno+1)%(mTcpServer.nrcli+1)==0)||g1.turno==-1 ){
                    System.out.println("");
                    g1.hayFicha = true;
                    g1.turno++;
                    if(g1.turno!=-1){puntajes[(g1.turno+mTcpServer.nrcli)%(mTcpServer.nrcli+1)]+=g1.borrarLineaHorizontal();}
                    g1.escogerSigFicha(g1.fichaActual);
                    g1.crearFicha(g1.tablero, g1.fichaActual, g1.bloquesFicha);
//                    g1.imprimir(g1.tablero);///
                    jPanel1.repaint();
                    enviarObjetos enviarObj = new enviarObjetos(g1,puntajes,mTcpServer.nrcli);
                    ServidorEnvia(enviarObj);
//                    mostrarPuntajes();
//                    if(g1.turno!=0){jLabel10.setText("Puntaje: "+puntajes[(g1.turno-1)%(mTcpServer.nrcli+1)]+" Turno: "+g1.turno+", Turno de jugador: "+g1.turno%(mTcpServer.nrcli+1));}
                }

                if (g1.juegoTerminado) {
//                    g1.anunciarGanador();
                    int ganadorId = 0; 
                    int maxPuntaje = -1;
                    for (int i = 0; i < mTcpServer.nrcli; i++) {
                        if (puntajes[i] > maxPuntaje) { 
                            maxPuntaje = puntajes[i]; 
                            ganadorId = i; 
                        } 
                    } 
                    jLabel10.setText("Ganador: Jugador " + ganadorId + " con " + maxPuntaje); 
                    break;
                }
                jPanel1.repaint();
                mostrarPuntajes();
                if(g1.turno!=0){jLabel11.setText("JUGADOR: SERVIDOR "+0);jLabel10.setText("Puntaje: "+puntajes[0]+" Turno: "+g1.turno+", Turno de jugador: "+g1.turno%(mTcpServer.nrcli+1));}
    //            System.out.print("Puntaje:" + g1.puntajeTotal + " Ingrese (a), (s), (d), (g), (u) o (e) para salir:");
  
//                String entrada = sc.next();
//
//                if(entrada.equals("a") || entrada.equals("s") || entrada.equals("d") || entrada.equals("g") || entrada.equals("u")){
//                    switch (entrada) {
//                        case "a" -> g1.moverIzquierda();
//                        case "s" -> g1.moverAbajo();
//                        case "d" -> g1.moverDerecha();
//                        case "g" -> g1.girarHorario();
//                        case "u" -> g1.girarAntihorario();
//                    }
//                    g1.imprimir(g1.tablero);
//                    jPanel1.repaint();
//                } else if(entrada.equals("e")){
//                    break;
//                }
                try {
                    Thread.sleep(10); 
                } catch (InterruptedException e) { break; }
            }
        }).start();
    }
    
    void iniciar(){
       new Thread(
            new Runnable() {

                @Override
                public void run() {
                      mTcpServer = new TCPServer50(
                        new TCPServer50.OnMessageReceived(){
                            @Override
                            public void messageReceived(Object message){
                                ServidorRecibe(message);
                            }
                        }
                    );
                    mTcpServer.run();                   
                }
            }
        ).start();

        String salir = "n";
        sc = new Scanner(System.in);
        System.out.println("Servidor bandera 01");
        while( !salir.equals("s")){
            salir = sc.nextLine();
            ServidorEnvia(salir);
        }
        System.out.println("Servidor bandera 02"); 
    }
    void ServidorRecibe(Object llego){
        System.out.println("SERVIDOR40 recibio Tablero. " );
        ServidorEnvia(llego);
        enviarObjetos tableroRecibido = (enviarObjetos) llego;
        g1=tableroRecibido.getGame();
        this.puntajes = tableroRecibido.getPuntajes();
        
        jPanel1.repaint();
 
//       if (llego.matches("^envia \\d+$")){
//            String outCliente[] = llego.split("\\s");
//            int numeroObt = Integer.parseInt(outCliente[1]);
//            System.out.println("Numero obtenido!!!: "+ numeroObt);
//       }

        
   }
    void ServidorEnvia(Object envia){
        if (mTcpServer != null) {
           mTcpServer.sendMessageTCPServer(envia);
        }
    }
    public void mostrarPuntajes() {
        jTextArea1.setText(""); //
        for (int i = 0; i < puntajes.length; i++) { //
            jTextArea1.append("Jugador " + i + ": " + puntajes[i] + "\n"); //
        } //
    }
    public static void main(String[] args) {
        JFrame ventana = new JFrame("Tetris Multijugador");
        TetrisPanelServer panel = new TetrisPanelServer();
        
        ventana.add(panel);
        ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ventana.pack(); 
        
        ventana.setLocationRelativeTo(null); 
        ventana.setVisible(true);
        panel.setFocusable(true);
        panel.requestFocusInWindow();
        panel.iniciar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
